### ISSUE TITLE
Sorry on starting a new issue. trying to get offsets

### ISSUE THREAD

**Issue by legendkiller0812** [pixeltris/ModTMNF#2]
https://github.com/pixeltris/ModTMNF/blob/897196292350fe1cb01018900ffa3b10ccccab5c/ModTMNF/Game/AddressTable/TMNF/ST.cs#L21

Sorry on starting a new issue. Could you tell me how you obtained the offsets for these classes? trying to find offsets for some game state info that I am interested in.

**Comment by pixeltris** [comment]
It has been a few years since I touched so I'm not really sure but I assume I used a combination of IDA and ollydbg to find addresses with the help of the .map function symbols. Unfortunately there aren't any symbols for global addresses or structures but the reflection system gives you the offsets to many classes.
